FROM balenalib/raspberry-pi-alpine-node

# Install python/pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

# Install miscellaneous
RUN apk add make

WORKDIR /app_frontend

# Vue.JS
RUN npm i -g vue @vue/cli @vue/cli-service

EXPOSE 3030

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3030

# Dependencies from package.json and start the server
ENTRYPOINT npm install && npm run build && npm run start
