FROM balenalib/raspberry-pi-alpine-node

# Install python/pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

# Install miscellaneous
RUN apk add make gcc g++

WORKDIR /app_backend

# Install dependencies required for project
RUN npm i -g @nestjs/cli

EXPOSE 3001

ENTRYPOINT npm install && npm run start:prod

# command: docker attach backend_app
